services:
  - type: web
    name: interview-server
    env: node
    buildCommand: cd server && pnpm install --no-frozen-lockfile && pnpm build
    startCommand: cd server && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false 